### ISSUE TITLE
Wrong position of input frame when typing in Electron/Chromium based program with a HiDPi screen

### ISSUE THREAD

**Issue by AlynxZhou** [ibus/ibus#1988]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch Linux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.26

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Atom
Chrome
All Electron(Chromium) based program.

IBus version?: 
(Run `ibus version`)
IBus 1.5.17

Issue description:
IBus got a wrong position in Electron or Chrome programs, I have a 4K screen with 200% scale, it always shows Chinese frame out of screen bottom, and I cannot see what character in the frame.

Steps to reproduce:
1. Run Chrome with a hidpi screen.
1. Use ibus-rime Chinese (I think it's not a rime specific issue but I am using RIME)
1. Type.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
How do you configure the 200% scale?
Can you attach the screenshot in this report?
``% gnome-screenshot -i``

**Comment by fujiwarat** [comment]
ping

**Comment by AlynxZhou** [comment]
@fujiwarat Sorry for reply late, I set it in gnome-settings, and I cannot give you screenshot because ibus select window is out of screen, so if I grab the screen you cannot find it in the photo, and only in chromium based apps it disappear.

**Comment by AlynxZhou** [comment]
![screenshot from 2018-03-24 17-33-57](https://user-images.githubusercontent.com/8444615/37862551-a7aefaf2-2f89-11e8-96b3-e14619cf7028.png)
Checked again and I can give you this image, you can see I am typing in the upper side of screen and it shows lower than the cursor position, if I type in the lower part of screen input frame will be out of screen.

**Comment by fujiwarat** [comment]
>  I set it in gnome-settings

Do you mean to set org.gnome.desktop.interface scaling-factor 2 ?
ibus had a problem in the scaling-factor but it has been fixed in ibus 1.5.17.

I cannot reproduce your problem with scaling-factor 2 and atom.
![Screenshot with ibus-rime](https://user-images.githubusercontent.com/105929/37892260-355078e8-3112-11e8-809d-48bad7c3a395.png)

I don't think the status icon of ibus-rime is "中" and I wonder if you use ibus-rime.
Can you check your engine with `ibus engine` command?

**Comment by AlynxZhou** [comment]
@fujiwarat strange, the screenshot is ibus libpinyin and both libpinyin and rime have problem on my PC, so I guess it's a problem of ibus itself.

Have you tried Wayland? And I think maybe it will happen when you get more lines and typing in the bottom of window because my ibus works like it set position doubled, when you are near left top the offset is small but in the bottom it has a big offset and goes out of screen...

**Comment by AlynxZhou** [comment]
@fujiwarat `gsettings get org.gnome.desktop.interface scaling-factor` gives me a default value of 0, scale 200% is in gnome-control-center -> display. But if I set it to 100%, it still get wrong position...

**Comment by AlynxZhou** [comment]
Plus `gsettings set org.gnome.desktop.interface scaling-factor 2` didn't help, still wrong position...

**Comment by AlynxZhou** [comment]
@fujiwarat Retested. `gsettings set org.gnome.desktop.interface scaling-factor 2` never worked and it did't change my desktop...Only the change in gnome control center works that when set to 100% is ok but to small, set to 200% caused this bug.

**Comment by fujiwarat** [comment]
> Have you tried Wayland? 

Yes, gsettings sclaing-factor works fine.

> And I think maybe it will happen when you get more lines and typing in the bottom of window because my ibus works like it set position doubled

I don't see such a problem.

> scale 200% is in gnome-control-center -> display

I think the GUI option of 200% appears for the high resolutions only. And the option does not enlarge my desktop. Seems VirtualBox with my monitor + intel HD 530 card does not work that option.

> `gsettings set org.gnome.desktop.interface scaling-factor 2` never worked and it did't change my desktop...

After I changed the resolution with gnome-control-center, I also no longer does not enlarge my desktop.
I don't know how to reset the condition. But when I create a new user account again, the gsettings scaling-factor works fine with the default resolution.

>  I guess it's a problem of ibus itself.

I guess it's not a problem in ibus at present.

gdk_window_get_scale_factor() works fine with the scaling-factor setting and I don't notice other APIs so I guess the 200% in gnome-control-center could reflect the value of gdk_window_get_scale_factor() .
https://github.com/ibus/ibus/commit/6a3301db85e77e0652f7e00894cce493b6a942f6

**Comment by AlynxZhou** [comment]
@fujiwarat OK, thank you for your work, maybe I should reinstall my system, what a strange thing...

**Comment by AlynxZhou** [comment]
@fujiwarat excuse me but what's your gnome version? I have searched this page and maybe related to this. https://unix.stackexchange.com/questions/400188/cannot-enable-hidpi-from-gnome-tweak-tool
Don't know what happened to my gnome...

**Comment by fujiwarat** [comment]
I tried GNOME 3.26 in Fedora 27 to follow your environment.
Now I tried GNOME 3.27.91 in Fedora 28 and I can configure scale 200% with `gnome-control-center display` and I cannot reproduce your problem.
So I suggest you to update your GNOME to 3.28.

**Comment by fujiwarat** [comment]
My default was 920x774 and I tried 1600x1200, 1920x1440, 1920x1200 for the record.

**Comment by Superdanby** [comment]
HI,
I think I'm experiencing the same issue. But strangely, it only affects my Chrome now. My Atom used to be affected as well if I remembered correctly.

![image](https://user-images.githubusercontent.com/17717083/38179463-3af9c3f0-3656-11e8-853c-92e8aa74c11c.png)

![image](https://user-images.githubusercontent.com/17717083/38227218-ce28c5a2-372f-11e8-9f57-6b338320382b.png)


I'll try upgrading to Fedora 28 beta when it is released today and see if Gnome 3.28 resolves my problem.

**Comment by fujiwarat** [comment]
I can reproduce your issue with chrome in Fedora 28 but I think it's a chrome issue.
I'm not sure but it might be a workaround not to override Chrome prediction with IBus lookup window.

**Comment by Superdanby** [comment]
Sorry, I don't know. I didn't even notice it had been fixed until I saw this thread. 
Here are my specs:
OS: Fedora 28 beta
Session: Wayland
```bash
atom --version
Atom: 1.25.0
Electron: 1.7.11
Chrome : 58.0.3029.110
Node: 7.9.0
```
```bash
ibus version
IBus 1.5.18
```
Hope this helps.

**Comment by fujiwarat** [comment]
@AlynxZhou I think you don't have to update ibus to 1.5.18.
ibus 1.5.17 or later has the fix of https://github.com/ibus/ibus/commit/6a3301db85e77e0652f7e00894cce493b6a942f6 .
I have no time to install Arch at the moment since the installation is complicated.
It would be great if you can try other distributions which uses GNOME 3.28 besides Arch.

**Comment by zl1775** [comment]
Same issue still persists in Ubuntu 18.04, which uses ibus 1.5.17 and GNOME 3.28. Only in Chrome does it exist. Firefox does not suffer from this issue.

**Comment by fujiwarat** [comment]
Regarding to chrome, I think it would be good to file a bug in chrome.

**Comment by Svtter** [comment]
@zl1775 @AlynxZhou Fixed in 70.0.3538.67.

**Comment by hanyihong0324** [comment]
In my case it just be opposite of @Superdanby , in Chrome it goes well but wrong position in Atom.
![screenshot from 2018-11-13 21-50-27](https://user-images.githubusercontent.com/17589280/48414909-42b07400-e78f-11e8-9542-d359f094ab0d.png)
![screenshot from 2018-11-13 21-50-57](https://user-images.githubusercontent.com/17589280/48414924-49d78200-e78f-11e8-8eb1-6232d02a6ced.png)
I using Ubuntu 18.10 with Gnome 3.30 in Wayland on a 14 inch 2560*1440 screen and set scale rate to 200% in Gnome settings. Chrome is version 72.0.3602.2 (Official Build) dev (64-bit) . Atom is version 1.33.0-beta0 x64. IBus is version 1.5.19.

**Comment by AlynxZhou** [comment]
chromium72 fixed it, but the chromium built in Electron has not been
updated.

**Comment by hanyihong0324** [comment]
Thanks for your reply! I will wait Atom team to upgrade their Electron version.

**Comment by AlynxZhou** [comment]
@hanyihong0324 If u want fix this temporarily, u can do following:

```
$ cp /usr/bin/atom /usr/bin/atom-fix
```

Edit `/usr/bin/atom-fix`, it is a shell script, find

```
"$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@"
```

replace this line with

```
GDK_SCALE=1 GDK_DPI_SCALE=1 "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@"
```

then find

```
nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
```

replace it with

```
GDK_SCALE=1 GDK_DPI_SCALE=1 nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
```

yes, just add `GDK_SCALE=1 GDK_DPI_SCALE=1` to the head which line executes Atom binary, passing those ENV will fix this bug temporarily by telling Electron to ignore GDK scale factor. Each time u want use atom, use `atom-fix` instead.

If u prefer launch it in DE, u can also create a desktop entry, fill file `.local/share/applications/atom-fix.desktop` with following content

```
[Desktop Entry]
Name=Atom (Fix)
Comment=A hackable text editor for the 21st Century
GenericName=Text Editor
Exec=/usr/bin/atom-fix %F
Icon=atom
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
StartupWMClass=Atom (Fix)
```

then click Atom (Fix) every time.

If u are using Atom Beta, please replace script name by yourself, because I only use Atom Stable.

**Comment by hanyihong0324** [comment]
I solved this problem by the solution [above](https://github.com/ibus/ibus/issues/1988#issuecomment-438559579). If anyone use atom-beta like me, it is not enough to only change these two lines in the script. It will get a error said "nohup: failed to run command '/usr/share/atom/atom': No such file or directory". The reason is in the line 12~25, here is a switch statement, when you change the name of this script to other name like "atom-fix" or "atom-beta-fix", it will mismatch every expression and try to run "atom" (Atom Stable). When you use Atom Stable it will be OK, but for atom-beta user, it can not find a atom-stable install and will get an error.

So the simplest solution is to change the word "stable" to "beta". And everything goes well.

**Comment by DaVinci42** [comment]
got the same issue for slack, the alternative approach is set `ENV` in `.desktop` file.
```
/usr/share/applications/slack.desktop 

Exec=env LD_PRELOAD=/usr/lib/libcurl.so.3 GDK_SCALE=1 GDK_DPI_SCALE=1 /usr/bin/slack %U
```

the `LD_PRELOAD` is already there, maybe different on other distributions. just add `GDK_SCALE=1 GDK_DPI_SCALE=1`

**Comment by loynoir** [comment]
Hi, @fujiwarat 

I have this problem too, under
- OS: ArchLinux
- Gnome: 40.4
- Session: wayland
- App with WRONG position: **Firefox**, and app mentioned above
- App with CORRECT position: gnome-terminal
- ibus: 1.5.25
- input method: `ibus-uniemoji`

Reproduce: 
- all settings are firefox default settings
- nothing tweaked

I guess, maybe replace `Electron/Chromium based program` to `program`?

**Comment by fujiwarat** [comment]
@loynoir I think your problem is not this one.

**Comment by loynoir** [comment]
@fujiwarat 
Weird, position in firefox is correct now, as same as I updated system weeks ago.  😂
All I did is follow every step archlinux wiki hardware acceleration again. 
But pos in chrome based still wrong.

**Comment by loynoir** [comment]
> More recent versions of Firefox support opting into Wayland mode via an environment variable. 
```sh
env MOZ_ENABLE_WAYLAND=1 firefox
```
Then pos is correct

**Comment by AlynxZhou** [comment]
> Strange. On Arch, mine only behave normally in Chromium based apps, but wrong position in gtk apps like below:
> 
> ![image](https://user-images.githubusercontent.com/20430813/223308864-7c44b2af-90d2-433c-b32d-d7bdfbf38932.png)
> 
> But in Fedora everything works well.

Did you set scale related things except Settings->Display? Maybe xrandr, also did you try the gnome-terminal (which still uses GTK3)?

**Comment by mariohide** [comment]
> > Strange. On Arch, mine only behave normally in Chromium based apps, but wrong position in gtk apps like below:
> > ![image](https://user-images.githubusercontent.com/20430813/223308864-7c44b2af-90d2-433c-b32d-d7bdfbf38932.png)
> > But in Fedora everything works well.
> 
> Did you set scale related things except Settings->Display? Maybe xrandr, also did you try the gnome-terminal (which still uses GTK3)?

Hi, finally I found it's a gmome + x11 problem, that's why things were ok on Fedora (it ships with wayland by default).

While I need to use x11, now I'm using fcitx5 + kim panel and everything works.

**Comment by bsdelf** [comment]
I have this issue in Xfce desktop with a 4K display (Dell 2415Q):

- xfce: 4.18
- ibus: 1.5.28
- ibus-rime: 1.5.0
- ibus-gtk+3: 1.5.28
- gtk+3: 3.24.38

environment variables:

```
export QT_AUTO_SCREEN_SCALE_FACTOR=2
export QT_SCALE_FACTOR=2
export GDK_SCALE=2
export GDK_DPI_SCALE=1
```

the xfce window manager theme for 4K display is `Default-xhdpi`.

while fcitx5 (rime) works fine with above settings.


> ![screenshot from 2018-03-24 17-33-57](https://user-images.githubusercontent.com/8444615/37862551-a7aefaf2-2f89-11e8-96b3-e14619cf7028.png) Checked again and I can give you this image, you can see I am typing in the upper side of screen and it shows lower than the cursor position, if I type in the lower part of screen input frame will be out of screen.

**Comment by bsdelf** [comment]
It seem only GTK based applications like chrome and thunar are affected, I use konsole as terminal, it's not affected at all.

![image](https://github.com/ibus/ibus/assets/555268/65a7b101-074e-4fe2-9967-a9144285ff7c)
