### ISSUE TITLE
1.5.28: parallel build fails becauee missin ibusenumtypes.h

### ISSUE THREAD

**Issue by kloczek** [ibus/ibus#2501]
looks like parallel build fails on missimg `ibusenumtypes.h`
```console
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-1.5.28/src'
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I..  -DG_LOG_DOMAIN=\"IBUS\" -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DIBUS_CACHE_DIR=\""/var/cache/ibus"\" -DIBUS_DATA_DIR=\"/usr/share/ibus\" -DIBUS_DISABLE_DEPRECATION_WARNINGS -DIBUS_COMPILATION -DISOCODES_PREFIX=\"/usr\" -DX11_LOCALEDATADIR=\"/usr/share/X11/locale\"  -DENABLE_EMOJI_DICT   -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Os -c -o gen_internal_compose_table-ibuskeynames.o `test -f 'ibuskeynames.c' || echo './'`ibuskeynames.c
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-1.5.28/src'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-1.5.28/src'
/usr/bin/gcc -DHAVE_CONFIG_H -I. -I..  -DG_LOG_DOMAIN=\"IBUS\" -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DIBUS_CACHE_DIR=\""/var/cache/ibus"\" -DIBUS_DATA_DIR=\"/usr/share/ibus\" -DIBUS_DISABLE_DEPRECATION_WARNINGS -DIBUS_COMPILATION -DISOCODES_PREFIX=\"/usr\" -DX11_LOCALEDATADIR=\"/usr/share/X11/locale\"  -DENABLE_EMOJI_DICT   -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Os -c -o gen_internal_compose_table-gencomposetable.o `test -f 'gencomposetable.c' || echo './'`gencomposetable.c
In file included from gencomposetable.c:23:
./ibus.h:49:10: fatal error: ibusenumtypes.h: No such file or directory
   49 | #include <ibusenumtypes.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1100: gen_internal_compose_table-gencomposetable.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-1.5.28/src'
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-1.5.28/src'
```
Found that workaroud is to execute `make -C src ibusenumtypes.h` before start `all` target.
Looks like somewhere is missing dependency rule.

**Comment by gunnarhj** [comment]
This problem has been reported to Debian too:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034090

**Comment by fujiwarat** [comment]
I think ibus-1.5.28.tar.gz includes ibusenumtypes.h

**Comment by kloczek** [comment]
I'm usimg tar ball autogenerated from git tag.
Nevertheless issue is in make dependencies definions.

**Comment by gunnarhj** [comment]
@fujiwarat wrote:
>  think ibus-1.5.28.tar.gz includes ibusenumtypes.h

It does, but if you build a second time, the file gets deleted and not recreated before it's needed.

**Comment by fujiwarat** [comment]
@kloczek 

> I'm usimg tar ball autogenerated from git tag.

Please use the tarball instead.  I don't assume every build issue should be fixed with git.

**Comment by fujiwarat** [comment]
@gunnarhj 

> It does, but if you build a second time, the file gets deleted and not recreated before it's needed.

Do you mean to run make after `make clean`?

How about this?
```
diff --git a/src/Makefile.am b/src/Makefile.am
index c2e8daa6..adc7f04a 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -194,6 +194,7 @@ gen_internal_compose_table_SOURCES = \
     ibuserror.c         \
     ibuskeynames.c      \
     ibuskeyuni.c        \
+    ibusenumtypes.h     \
     $(NULL)
 gen_internal_compose_table_CFLAGS = $(AM_CFLAGS)
 gen_internal_compose_table_LDADD = \
```

**Comment by gunnarhj** [comment]
> Do you mean to run make after make clean?

Yes.

> How about this?
> 
> ```
> diff --git a/src/Makefile.am b/src/Makefile.am
> index c2e8daa6..adc7f04a 100644
> --- a/src/Makefile.am
> +++ b/src/Makefile.am
> @@ -194,6 +194,7 @@ gen_internal_compose_table_SOURCES = \
>      ibuserror.c         \
>      ibuskeynames.c      \
>      ibuskeyuni.c        \
> +    ibusenumtypes.h     \
>      $(NULL)
>  gen_internal_compose_table_CFLAGS = $(AM_CFLAGS)
>  gen_internal_compose_table_LDADD = \
> ```

Nope. I still get:

```
./ibus.h:49:10: fatal error: ibusenumtypes.h: No such file or directory
   49 | #include <ibusenumtypes.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

@kloczek's mentioned woraround makes a difference, though.

**Comment by fujiwarat** [comment]
> Nope. I still get:

Then I have no idea. My suggestion works fine in my env.

**Comment by gunnarhj** [comment]
>> Nope. I still get:
>
> Then I have no idea. My suggestion works fine in my env.

Well, it does make a difference for me if building from source. But when using the release tarball, where `src/Makefile.in` has been generated in advance, I had to make the same change in `src/Makefile.in`. Then it stopped complaining about `ibusenumtypes.h` not existing.

I use the Debian tools for building rather than running the `make *` commands manually, and I suppose that `src/makefile.in` never gets regenerated for me. Thanks for the solution!

Unfortunately this made another build issue surface... When building from the release tarball a second time, I get this error:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"IBUS\" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -pthread -DIBUS_CACHE_DIR=\"/var/cache/ibus\" -DIBUS_DATA_DIR=\"/usr/share/ibus\" -DIBUS_DISABLE_DEPRECATION_WARNINGS -DIBUS_COMPILATION -DISOCODES_PREFIX=\"/usr\" -DX11_DATA_PREFIX=\"/usr\" -DENABLE_EMOJI_DICT -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/home/gunnar/devel/temp/ibus-1.5.28=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -pedantic -c ibusutil.c  -fPIC -DPIC -o .libs/ibusutil.o
libtool:   error: 'ibusunicode.lo' is not a valid libtool object
```

But I suppose that's unrelated to this issue, so please feel free to disregard it for now. I may get back if it proves to be a real problem for someone.

**Comment by fujiwarat** [comment]
@gunnarhj Thank you for your check.

>  I had to make the same change in src/Makefile.in. Then it stopped complaining about ibusenumtypes.h not existing.

Right. You need to run `autoreconf -f -i -v` or `automake src/Makefile && ./config.status src/Makefile`.
I will integrate my patch.

**Comment by mattst88** [comment]
This is definitely not fixed. I see the error when building from the main branch today with `make -j8`.

**Comment by mattst88** [comment]
In continuing to investigate, I've spotted at least two other manifestations of the dependency problems:

````
ibusshare.c:27:10: fatal error: ibusresources.h: No such file or directory
   27 | #include "ibusresources.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
````

````
ibusproperty.c:25:10: fatal error: ibusenumtypes.h: No such file or directory
   25 | #include "ibusenumtypes.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
````

**Comment by mattst88** [comment]
I notice that it appears that `libibus-1.0.la` is being built/linked twice?

````
libtool:   error: 'ibusxevent.lo' is not a valid libtool object
make[4]: *** [Makefile:989: libibus-1.0.la] Error 1
make[4]: *** Waiting for unfinished jobs....
  CCLD     libibus-1.0.la
  CCLD     libibus-1.0.la
  CCLD     emoji-parser
./.libs/libibus-1.0.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
````

Automake is such a disaster.

**Comment by mattst88** [comment]
🤦🤦🤦🤦🤦🤦🤦

````
ibusemojigen.h:
	$(MAKE) $(AM_MAKEFLAGS) dicts/emoji-en.dict
[...]
ibusunicodegen.h:
	$(MAKE) $(AM_MAKEFLAGS) dicts/unicode-blocks.dict
````

You can't call `$(MAKE)` from automake with no dependencies specified and expect anything to work.
