### ISSUE TITLE
ibus-x11 assert failure: realloc(): invalid next size when typing in Zed

### ISSUE THREAD

**Issue by smitbarmase** [ibus/ibus#2789]
### Distribution and Version

Ubuntu 25.04 ("Plucky Puffin") – arm64 (also reproducible on x86-64) 

### Desktop Environment and Version

GNOME 48

### Session Type

X11

### Application and Version

Zed 0.198.6

### IBus version

Ubuntu 25.04: 1.5.32~rc2-1  (Also, Fedora 42: 1.5.32-1 and Ubuntu 25.10: 1.5.32-2)

### Issue Description

`ibus-x11` aborts with `SIGABRT` and the message **`realloc(): invalid next size`** shortly after an XIM client starts sending key events. After the crash, the `ibus-x11` process disappears. Restarting iBus brings `ibus-x11` back and the next few keystrokes crash it again.

From Apport (Ubuntu 25.04, arm64):

* ExecutablePath: `/usr/libexec/ibus-x11`
* Title: `ibus-x11 assert failure: realloc(): invalid next size`
* Signal: `6 (SIGABRT)`
* ProcCmdline: `/usr/libexec/ibus-x11 --kill-daemon`
* SourcePackage: `ibus`
* ApportVersion: `2.32.0-0ubuntu5.3`

### Steps to Reproduce

```bash
A) Using Zed (X11 build)

1. Open Zed on Ubuntu 25.04 (X11) and type a few characters → `ibus-x11` crashes.
2. Close Zed and run:

   
   ps aux | grep ibus
   

   Example output (note: no `ibus-x11` present):

   
   smit 26668 ... /usr/bin/ibus-daemon --panel disable --xim
   smit 26679 ... /usr/libexec/ibus-memconf
   smit 26680 ... /usr/libexec/ibus-extension-gtk3
   smit 26690 ... /usr/libexec/ibus-portal
   smit 26702 ... /usr/libexec/ibus-engine-simple
   

   Relaunching Zed now “works” only because input is no longer going through XIM.

3. With Zed closed, restart iBus:

   
   ibus restart
   

4. Launch Zed again and type a few characters → crash reproduces.


B) Using `xim-rs` example

Repo: https://github.com/Riey/xim-rs

1. On Ubuntu 25.04, run:

   
   cargo run --example x11rb_client --features="x11rb-client"
   
2. Type bunch of characters. `ibus-x11` crashes. Subsequent key presses yield:

   
   ERROR x11rb_client > X11Error: ... request_name: Some("SendEvent")
   
3. Confirm `ibus-x11` is gone:

   
   ps aux | grep ibus
   
4. `ibus restart` → run again → crash reproduces.
```

### Can you reproduce your problem when you restart ibus-daemon? (yes / no)

Yes. `ibus restart` reliably restores `ibus-x11`, and the next few keystrokes in the XIM client crash it again.

### Do you see any errors when you run ibus-daemon with the verbose option?

Nope. I ran `journalctl --user -f | grep -i ibus` doesn't seem to log anything. Maybe because it's crashing?

### Can you reproduce your problem with a new user account instead of the
current your account? (yes / no)

Yes, fresh install of Ubuntu 25.04 is easiest way to reproduce this. For Fedora 42 (ibus 1.5.32-1) and Ubuntu 25.10 (ibus 1.5.32-2) which by default comes with Wayland, I had to install x11 manually to reproduce it on them.

### Add any other context about the problem here.

Affected versions of ibus: `1.5.32~rc2-1`, `1.5.32-1`, `1.5.32-2`.

Related upstream discussion (Zed): [https://github.com/zed-industries/zed/issues/29083](https://github.com/zed-industries/zed/issues/29083)

**Comment by NickJAllen** [comment]
This crash affects many other applications. For example Bitwig Studio and VS Code.

**Comment by fujiwarat** [comment]
Hope this was fixed by https://github.com/ibus/ibus/commit/fd18bda4cb1ef65b3f7b902e67cc0b661a369810
Fedora 42 has the fix with ibus-1.5.32-2.fc42 and you could try with `dnf update ibus`.

**Comment by abique** [comment]
FYI, this is a super major issue and the fix is still not deployed on Archlinux.

This issue leads to broken text input in Bitwig after only typing a few characters, it gives a terrible impression of the Linux desktop.

**Comment by smitbarmase** [comment]
I have verified this on Fedora 42 with ibus-1.5.32-2.fc42, and ibus no longer crashes. Thank you!
